Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.omnibus.chef_version = :latest

  config.vm.provision :shell, inline: "sudo locale-gen #{ENV['LANG']} && " \
    'sudo dpkg-reconfigure locales'
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  end
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['cookbooks']
    chef.add_recipe 'apt'
    chef.add_recipe 'mongodb::10gen_repo'
    chef.add_recipe 'mongodb'
    chef.add_recipe 'mysql::server'
    chef.add_recipe 'postgresql::server'
    chef.json = {
      'mysql' => {
        'server_root_password' => 'pseudorandom',
        'server_repl_password' => 'pseudorandom',
        'server_debian_password' => 'pseudorandom'
      },
      'mongodb' => {
        'package_version' => '2.4.9'
      },
      'postgresql' => {
        'password' => { 'postgres' => 'pseudorandom' }
      }
    }
  end
  config.vm.provision :shell, inline: "echo \"#{`cat ./id_rsa.pub`}\" >> " \
    '~vagrant/.ssh/authorized_keys'
  config.vm.provision :shell, path: 'setup.sh'
end
