# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "lxc-precise64"
  config.vm.provider :lxc do |lxc|
    lxc.customize 'network.ipv4', '10.0.3.10/32'
  end
 
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['cookbooks']
    chef.add_recipe 'apt'
    chef.add_recipe 'mysql::server'
    chef.add_recipe 'mongodb::10gen_repo'
    chef.add_recipe 'mongodb'
    chef.json = {
      "mysql" => {
        "server_root_password" => "pseudorandom",
        "server_repl_password" => "pseudorandom",
        "server_debian_password" => "pseudorandom"
      },
      "mongodb" => {
        "package_version" => '2.4.9'
      }
    }
  end

  config.vm.provision :shell, inline: "echo \"#{`cat ~/.ssh/id_rsa.pub`}\" >> ~vagrant/.ssh/authorized_keys"
  config.vm.provision :shell, path: 'setup.sh'
end
